### PR TITLE
[staking] Fix unstake not clean selfstake

### LINKED ISSUE #4336: Candidate selfstake not clean after selfstake bucket unstaked
### What version of iotex-core image (or code branch) are you using?
v2.0.0

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
unstake a selfstake bucket

### What did you expect to see?
candidate selfstake amount becomes 0

### What did you see instead?
candidate selfstake amount not change, still equal 1.2M

### PR DESCRIPTION
**Pull request by envestcc**
# Description

Fixes #4336 , including two parts:
- clean selfstake when handling unstake action in staking protocol
- revise candiate selfstake at VanuatuBlockHeight

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by CoderZhi — APPROVED** [review]

File: action/protocol/staking/vote_reviser.go [hunk 1]
```diff
@@ -26,6 +26,7 @@ type (
 		ReviseHeights               []uint64
 		CorrectCandsHeight          uint64
 		SelfStakeBucketReviseHeight uint64
+		CorrectCandSelfStakeHeight  uint64
```
Comment (dustinxie) [inline action/protocol/staking/vote_reviser.go:29]: `UnstakedSelfStakeClearHeight` is a better name?

File: action/protocol/staking/vote_reviser.go [hunk 2]
```diff
@@ -47,6 +48,12 @@ func (vr *VoteReviser) Revise(ctx protocol.FeatureCtx, csm CandidateStateManager
 		case err != nil:
 			return err
 		}
+		if vr.shouldCorrectCandSelfStake(height) {
```
Comment (dustinxie) [inline action/protocol/staking/vote_reviser.go:51]: `shouldClearUnstakedSelfStake` is a better name, also should this be put after L57 `shouldReviseSelfStakeBuckets()`?

**Review by dustinxie — APPROVED** [review]
