### PR TITLE
[blockdao] Fix program unstopable when blockdao is checking indexer

### LINKED ISSUE #4158: SIGINT won't stop the program when syncing blocks
### What version of iotex-core image (or code branch) are you using?
v1.13
### What did you do? If possible, provide a recipe for reproducing the error.
ctrl+c to stop the process
### What did you expect to see?
The program was still running 
### What did you see instead?
The program will exit in a few seconds

### PR DESCRIPTION
**Pull request by envestcc**
# Description

Fixes #4158 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: blockchain/blockdao/blockindexer.go [hunk 1]
```diff
@@ -82,6 +82,12 @@ func (bic *BlockIndexerChecker) CheckIndexer(ctx context.Context, indexer BlockI
 		}
 	}
 	for i := startHeight; i <= targetHeight; i++ {
+		// ternimate if context is done
+		select {
```
Comment (Liuhaai) [inline blockchain/blockdao/blockindexer.go:86]: if ctx.Err() != nil {
return err
}
balabla

**Review by CoderZhi — APPROVED** [review]
