### PR TITLE
Fix test TestProtocol_ClaimReward

### LINKED ISSUE #2521: go test -run TestProtocol_ClaimReward
### What version of iotex-core are you using (`ioctl version`)?
latest master

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
```go
cd action/protocol/rewarding
go test -run TestProtocol_ClaimReward
```

### What did you expect to see?
test should pass

### What did you see instead?
test fail
if you run `go test` it will pass
but `go test -run TestProtocol_ClaimReward` should pass by itself as well

### PR DESCRIPTION
**Pull request by Liuhaai**
fix #2521 

## Issue description:
Run `go test -run TestProtocol_ClaimReward` will fail, but run `go test` will pass.

## Reason:
When run `go test`, func TestProtocol_Handle runs before func TestProtocol_ClaimReward. The initial balance of account was changed to 1000000 on Line 302 in `protocol_test.go` 
```
cfg.Genesis.Rewarding.InitBalanceStr = "1000000"
```
However, if func TestProtocol_Handle runs alone, its initial balance is 100000000000000000000000000

## Solution:
Use a variable `initBalance` to record the initial balance of account when entering func TestProtocol_Handle

### CODE REVIEW

**Review by dustinxie — APPROVED** [review]

File: action/protocol/rewarding/reward_test.go [hunk 1]
```diff
@@ -274,7 +280,8 @@ func TestProtocol_ClaimReward(t *testing.T) {
 		assert.Equal(t, big.NewInt(0), unclaimedBalance)
 		primAcc, err = accountutil.LoadAccount(sm, hash.BytesToHash160(claimActionCtx.Caller.Bytes()))
 		require.NoError(t, err)
-		assert.Equal(t, big.NewInt(1000010), primAcc.Balance)
+		initBalance = new(big.Int).Add(initBalance, big.NewInt(5))
+		assert.Equal(t, initBalance, primAcc.Balance)
```
Comment (dustinxie) [inline action/protocol/rewarding/reward_test.go:284]: can simplify to 
`assert.Equal(t, initBalance.Add(big.NewInt(5)), primAcc.Balance)`

**Review by CoderZhi — APPROVED** [review]
