### PR TITLE
Solve a bug in checkIndexers()

### LINKED ISSUE #2698: indexer sync performance slow after #2673
### What version of iotex-core are you using (`ioctl version`)?
commit at https://github.com/iotexproject/iotex-core/commit/7c758ab75007a17606563303816229b3d252778f

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
i am running indexer sync test on EVM chainID() change. It takes 16~17 seconds to index 5000 blocks. Here's log of first 30000 blocks:
```
{"level":"info","ts":1623103071.6737494,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":5000}
{"level":"info","ts":1623103087.57429,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":10000}
{"level":"info","ts":1623103103.059698,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":15000}
{"level":"info","ts":1623103118.8980942,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":20000}
{"level":"info","ts":1623103135.5412967,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":25000}
{"level":"info","ts":1623103151.6290169,"caller":"blockdao/blockdao.go:184","msg":"indexer is catching up.","ioAddr":"io1xv2yzj3m30fjwfs5yfv5slah7pj6sa8pmpq98q","indexer":0,"height":30000}
```

### What did you expect to see?
same sync speed

### What did you see instead?
with the commit in question, the first 5000 blocks takes 42 seconds, while block 25000~30000 quickly rise to 200 seconds
```
{"level":"info","ts":1623101858.9261827,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":5000}
{"level":"info","ts":1623101900.4941583,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":10000}
{"level":"info","ts":1623101994.3038423,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":15000}
{"level":"info","ts":1623102119.9937277,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":20000}
{"level":"info","ts":1623102283.2468967,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":25000}
{"level":"info","ts":1623102486.7054665,"caller":"blockdao/blockdao.go:186","msg":"indexer is catching up.","ioAddr":"io190ghqr8209aujl0er0gzx23y3phzzfr6w8q5lv","indexer":0,"height":30000}
```

### PR DESCRIPTION
**Pull request by Liuhaai**
fix #2698 
The issue is caused by reuse of context in [L164](https://github.com/iotexproject/iotex-core/blob/0796d378aaedf3b802fead0090a7f26669a0c37f/blockchain/blockdao/blockdao.go#L164). As block height increases, the context var becomes larger due to reuse.

### CODE REVIEW

File: blockchain/blockdao/blockdao.go [hunk 1]
```diff
@@ -161,12 +161,12 @@ func (dao *blockDAO) checkIndexers(ctx context.Context) error {
 			if err != nil {
 				return err
 			}
-			ctx, err = dao.fillWithBlockInfoAsTip(ctx, i-1)
+			ctxNew, err := dao.fillWithBlockInfoAsTip(ctx, i-1)
```
Comment (CoderZhi) [inline blockchain/blockdao/blockdao.go:164]: rename to `ctxWithTip`

**Review by CoderZhi — APPROVED** [review]

**Review by raullenchai — APPROVED** [review]
