### PR TITLE
[ioctl] action transfer supports 0x address 

### LINKED ISSUE #3901: [ioctl] action transfer should work with 0x address
### What would you like to be added
```
ioctl action transfer 0x35cb41ec685a30Bf5ebc3F935aEbB1a8391e5fD6
Error: failed to get recipient address: 0x35cb41ec685a30Bf5ebc3F935aEbB1a8391e5fD6: invalid IoTeX address
```

### Why is this needed
1. accept 0x address will make it more user-friendly
2. at the same time, it needs to be a valid 0x address (20-bytes)

### How important you think this is for IoTeX
- [x] must have
- [] should have
- [] nice to have

### Additional information
Let us know any background or context that would help us better understand the request (for example the particular use-case that prompted this request)

### PR DESCRIPTION
**Pull request by millken**
# Description
as title, this changes is not only `action transfer`, other commands will be supported

Fixes #3901 

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Liuhaai — APPROVED** [review]

**Review by bitcoinfinancier — APPROVED** [review]

File: ioctl/util/util.go [hunk 1]
```diff
@@ -153,6 +154,14 @@ func GetAddress(in string) (string, error) {
 
 // Address returns the address corresponding to alias. if 'in' is an IoTeX address, returns 'in'
 func Address(in string) (string, error) {
+	// if in is an eth address, convert it to IoTeX address
+	if len(in) == 42 && (in[:2] == "0x" || in[:2] == "0X") {
```
Comment (dustinxie) [inline ioctl/util/util.go:158]: use `go-ethereum package common.IsHexAddress`

Comment (millken) [reply ioctl/util/util.go]: done

**Review by dustinxie — APPROVED** [review]
