### PR TITLE
[actsync] Fix data race

### LINKED ISSUE #4399: sporadic data race in actionsync test
### What version of iotex-core image (or code branch) are you using?
master

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
make test

### What did you expect to see?
test pass

### What did you see instead?
This is a sporadic test failure, I've seen this 2 times in the past month
```
==================
WARNING: DATA RACE
Write at 0x00c000126010 by goroutine 10:
  runtime.closechan()
      /usr/local/go/src/runtime/chan.go:357 +0x0
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).Stop()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:76 +0x165
  github.com/iotexproject/iotex-core/actsync.TestActionSync.func3()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync_test.go:59 +0x84
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x30
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x383
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x55

Previous read at 0x00c000126010 by goroutine 12:
  runtime.chansend()
      /usr/local/go/src/runtime/chan.go:160 +0x0
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).trigger()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:154 +0xc4
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).triggerSync.func1()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:138 +0x107
  sync.(*Map).Range()
      /usr/local/go/src/sync/map.go:476 +0x3cd
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).triggerSync()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:137 +0x4e4
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).Start.func2()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:64 +0x3d

Goroutine 10 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0xd5c
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2054 +0x158
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x383
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2052 +0x857
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1925 +0x16c5
  main.main()
      _testmain.go:49 +0x1e4

Goroutine 12 (running) created at:
  github.com/iotexproject/iotex-core/actsync.(*ActionSync).Start()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync.go:64 +0x265
  github.com/iotexproject/iotex-core/actsync.TestActionSync()
      /Users/dustin/iotexproject/iotex-core/actsync/actionsync_test.go:57 +0x4e6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x383
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x55
==================

```

### PR DESCRIPTION
**Pull request by envestcc**
# Description

Fixes #4399 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: actsync/actionsync.go [hunk 1]
```diff
@@ -95,7 +95,6 @@ func (as *ActionSync) Stop(ctx context.Context) error {
 		return err
 	}
 	close(as.quit)
-	close(as.syncChan)
```
Comment (envestcc) [inline actsync/actionsync.go:98]: do not close the channel, so it will not panic.

File: actsync/actionsync.go [hunk 2]
```diff
@@ -127,28 +126,33 @@ func (as *ActionSync) ReceiveAction(_ context.Context, hash hash.Hash256) {
...
+				log.L().Debug("action is recently requested", log.Hex("hash", hash[:]))
+				continue
+			}
+			msg.(*actionMsg).lastTime = time.Now()
+			// TODO: enhancement, request multiple actions in one message
+			if err := as.requestFromNeighbors(ctx, hash); err != nil {
+				log.L().Warn("Failed to request action from neighbors", zap.Error(err))
+				counterMtc.WithLabelValues("failed").Inc()
+			}
+		case <-as.quit:
```
Comment (envestcc) [inline actsync/actionsync.go:151]: quit immediately may cause data discard, but it should be acceptable when stop service

File: actsync/actionsync.go (hunk 1 above)
Comment (dustinxie) [reply actsync/actionsync.go:98]: better to close the channel, otherwise we are leaving a channel that may still have data (and possibly a memory leak)
can send to another chan in sync(), and wait that channel here
```
<- as.exit
```

File: actsync/actionsync.go (hunk 2 above)
Comment (dustinxie) [reply actsync/actionsync.go:151]: have another channel and close it here, so `Stop()` can receive from this channel, and continue close the service
```
as.exit <- struct{}{}
```

**Review by dustinxie — APPROVED** [review]

**Review by Liuhaai — APPROVED** [review]

**Comment by Liuhaai** [comment]
add unit tests for the fix
