### PR TITLE
cache receipts in workingset

### LINKED ISSUE #2359: node miss receipt in blockdao
```
Error: failed to get actions info: failed to get receipts of block 751: key = ef02000000000000 doesn't exist: not exist in DB
root@iotex-delegate-0:/# ioctl bc block 873 --verbose
Warn: Language en is not supported, English instead.

Error: failed to get actions info: failed to get receipts of block 873: key = 6903000000000000 doesn't exist: not exist in DB
root@iotex-delegate-0:/# ioctl bc block 738 --verbose
Warn: Language en is not supported, English instead.

Error: failed to get actions info: failed to get receipts of block 738: key = e202000000000000 doesn't exist: not exist in DB
root@iotex-delegate-0:/# ioctl bc block 874 --verbose
Warn: Language en is not supported, English instead.

Blockchain Node: 127.0.0.1:14014
{
  "hash": "ce6296f4a9efd276e9ed37b327c83ff69d4fd9db5baf2e8417498e85222e3a9f",
  "height": 874,
  "timestamp": {
    "seconds": 1596069900
  },
  "numActions": 1,
  "producerAddress": "io1ed2luwadkqgc4uu3elnpqxzzgla2h55nwf9l8l",
  "transferAmount": "0",
  "txRoot": "3195e784311d19647e85a6c04c865f7c462da1a5b000340484887efa8479db0f",
  "receiptRoot": "05d82c43d23cd9a697b2747e1d98efeb5b8a4efb3b5f5db0e4813e895f6662ba",
  "deltaStateDigest": "69a6f4c4c25422a2dd797658be92889b8e8c9c6f87f8cd84760d2d61040998a2",
  "logsBloom": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}
```

### PR DESCRIPTION
**Pull request by CoderZhi**
fix #2359

### CODE REVIEW

File: state/factory/factory.go [hunk 1]
```diff
@@ -540,7 +544,7 @@ func (sf *factory) PutBlock(ctx context.Context, blk *block.Block) error {
 		if !sf.skipBlockValidationOnPut {
 			err = ws.ValidateBlock(ctx, blk)
 		} else {
-			_, err = ws.Process(ctx, blk.RunnableActions().Actions())
+			err = ws.Process(ctx, blk.RunnableActions().Actions())
```
Comment (yutongp) [inline state/factory/factory.go:547]: do we need to set `blk.Receipts = receipts` in factory.PutBlock as well?
