### PR TITLE
fix dangling *big.Int.SetString

### LINKED ISSUE #3042: fix dangling *big.Int.SetString()
### What did you do? If possible, provide a recipe for reproducing the error.

```
package main

import (
	"fmt"
	"math/big"
)

func main() {
	i := new(big.Int)
	ans, ok := i.SetString("61xx44", 10)
	fmt.Println(i, ans, ok)
}
```
output: `61 <nil> false`
If the string value is illegal, the `i` will become invalid.

### What did you expect to see?
```
x, ok = new(big.Int).SetString(string, 10)
if !ok {
   return errors.New("...")
}
```

### What did you see instead?
```
x.SetString(string, 10)
```
Bugs can be found by searching ".SetString(" in the codebase

### PR DESCRIPTION
**Pull request by LuckyPigeon**
fix #3042

### CODE REVIEW

**Comment by Liuhaai** [comment]
Could you help fix the [test](https://app.circleci.com/pipelines/github/iotexproject/iotex-core/3999/workflows/0d3d2269-b176-4630-8b9e-673cd05e3a49/jobs/15940)?

**Comment by LuckyPigeon** [comment]
Sure!

**Review by CoderZhi — APPROVED** [review]

**Review by CoderZhi — CHANGES_REQUESTED** [review]
https://github.com/iotexproject/iotex-core/pull/3088/files#diff-e1473250fc752e2a838cf94f58e06e22f1dc006c1a897247a174a56a4e76f433R145 The test failure for this line seems critical. @Liuhaai

File: action/envelope.go [hunk 1]
```diff
@@ -140,7 +140,11 @@ func (elp *envelope) LoadProto(pbAct *iotextypes.ActionCore) error {
 	elp.nonce = pbAct.GetNonce()
 	elp.gasLimit = pbAct.GetGasLimit()
 	elp.gasPrice = &big.Int{}
-	elp.gasPrice.SetString(pbAct.GetGasPrice(), 10)
+	_, ok := elp.gasPrice.SetString(pbAct.GetGasPrice(), 10)
+	// elp gas price gets zero when pbAct.GetGasPrice is empty string
```
Comment (Liuhaai) [inline action/envelope.go:144]: Sometimes, it's better to explain with code instead of comment
```
if pbAct.GetGasPrice() == "" {
	elp.gasPrice = big.NewInt(0)
} else {
	elp.gasPrice, ok = new(big.Int).SetString(pbAct.GetGasPrice(), 10);
	if !ok {
	}
}
```

File: action/execution.go [hunk 2]
```diff
@@ -117,7 +117,10 @@ func (ex *Execution) LoadProto(pbAct *iotextypes.Execution) error {
 
 	ex.contract = pbAct.GetContract()
 	ex.amount = &big.Int{}
-	ex.amount.SetString(pbAct.GetAmount(), 10)
+	_, ok := ex.amount.SetString(pbAct.GetAmount(), 10)
```
Comment (Liuhaai) [inline action/execution.go:120]: As mentioned in the [issue](https://github.com/iotexproject/iotex-core/issues/3042),  the value of ex.amont will change even if there is an error when doing `SetString()`
Use `x, ok = new(big.Int).SetString(string, 10)` pattern instead

File: action/envelope.go [hunk 3]
```diff
@@ -139,8 +139,15 @@ func (elp *envelope) LoadProto(pbAct *iotextypes.ActionCore) error {
 	elp.version = pbAct.GetVersion()
 	elp.nonce = pbAct.GetNonce()
 	elp.gasLimit = pbAct.GetGasLimit()
-	elp.gasPrice = &big.Int{}
-	elp.gasPrice.SetString(pbAct.GetGasPrice(), 10)
+	if pbAct.GetGasPrice() == "" {
+		elp.gasPrice = big.NewInt(0)
+	} else {
+		gp, ok := new(big.Int).SetString(pbAct.GetGasPrice(), 10)
+		if !ok && pbAct.GetGasPrice() != "" {
```
Comment (Liuhaai) [inline action/envelope.go:146]: if !ok {
}

File: action/envelope.go [hunk 4]
```diff
@@ -139,8 +139,15 @@ func (elp *envelope) LoadProto(pbAct *iotextypes.ActionCore) error {
 	elp.version = pbAct.GetVersion()
 	elp.nonce = pbAct.GetNonce()
 	elp.gasLimit = pbAct.GetGasLimit()
-	elp.gasPrice = &big.Int{}
-	elp.gasPrice.SetString(pbAct.GetGasPrice(), 10)
+	if pbAct.GetGasPrice() == "" {
+		elp.gasPrice = big.NewInt(0)
+	} else {
+		gp, ok := new(big.Int).SetString(pbAct.GetGasPrice(), 10)
```
Comment (Liuhaai) [inline action/envelope.go:145]: Both `elp.gasPrice = gp` and `elp.gasPrice, ok := new(big.Int).SetString()` are ok. B/c elp.gasPrice is nil initially

File: state/account.go [hunk 5]
```diff
@@ -63,7 +63,10 @@ func (st *Account) FromProto(acPb *accountpb.Account) {
 	st.Nonce = acPb.Nonce
 	st.Balance = big.NewInt(0)
 	if acPb.Balance != "" {
-		st.Balance.SetString(acPb.Balance, 10)
+		_, ok := st.Balance.SetString(acPb.Balance, 10)
```
Comment (Liuhaai) [inline state/account.go:66]: new(big.Int).SetString()

File: tools/actioninjector.v2/internal/cmd/inject.go [hunk 6]
```diff
@@ -392,7 +392,10 @@ func inject(_ []string) string {
 	transferGasPrice := big.NewInt(rawInjectCfg.transferGasPrice)
 	executionGasPrice := big.NewInt(rawInjectCfg.executionGasPrice)
 	executionAmount := big.NewInt(rawInjectCfg.executionAmount)
-	loadTokenAmount, _ := big.NewInt(0).SetString(rawInjectCfg.loadTokenAmount, 10)
+	loadTokenAmount, ok := big.NewInt(0).SetString(rawInjectCfg.loadTokenAmount, 10)
```
Comment (Liuhaai) [inline tools/actioninjector.v2/internal/cmd/inject.go:395]: new(big.Int).SetString()

File: action/envelope.go (hunk 4 above)
Comment (LuckyPigeon) [reply action/envelope.go:145]: `elp.gasPrice, ok := new(big.Int).SetString()` can cause `expected identifier on the left side of :=` error.
Since `elp.gasPrice` has already declared, I use gp instead.

File: action/transfer.go [hunk 7]
```diff
@@ -112,8 +112,16 @@ func (tsf *Transfer) LoadProto(pbAct *iotextypes.Transfer) error {
...
 	tsf.recipient = pbAct.GetRecipient()
 	tsf.payload = pbAct.GetPayload()
-	tsf.amount = big.NewInt(0)
-	tsf.amount.SetString(pbAct.GetAmount(), 10)
+	if pbAct.GetAmount() == "" {
+		tsf.amount = big.NewInt(0)
+	} else {
+		amount, ok := new(big.Int).SetString(pbAct.GetAmount(), 10)
+		// tsf amount gets zero when pbAct.GetAmount is empty string
+		if !ok && pbAct.GetAmount() != "" {
```
Comment (Liuhaai) [inline action/transfer.go:120]: if !ok {

**Review by Liuhaai — APPROVED** [review]

**Review by CoderZhi — APPROVED** [review]
We need a full sync to make sure this PR won't break our chain in the next release. @Liuhaai

**Comment by Liuhaai** [comment]
> We need a full sync to make sure this PR won't break our chain in the next release. @Liuhaai

ok. Will do.
