### PR TITLE
[ioctl] fix -P flag ignoring password input

### LINKED ISSUE #4340: ioctl -P argument to input account password seems to be ignored
The `-P`flag of ioctl suposed to input the account password for signing in the command below seems to be ignored (it keeps asking for the password): 

```sh
ioctl jwt sign --with-arguments '{"exp":"1767024000","sub":"AnalyserAPI","scope":"Read"}' -s accountname -P testpassword

Enter password for #io1qr384jh3602cscwlwyr3nlyhcslujahkhmwmpj
```

### PR DESCRIPTION
**Pull request by dustinxie**
# Description
as title

Fixes #4340 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by envestcc — APPROVED** [review]

File: ioctl/cmd/action/action.go [hunk 1]
```diff
@@ -209,6 +209,10 @@ func fixGasLimit(caller string, execution *action.Execution) (*action.Execution,
 	return action.NewExecution(execution.Contract(), execution.Nonce(), execution.Amount(), res.Gas, execution.GasPrice(), execution.Data())
 }
 
+func PasswordByFlag() string {
+	return _passwordFlag.Value().(string)
+}
+
```
Comment (CoderZhi) [inline ioctl/cmd/action/action.go:215]: move to `ioctl/cmd/account` to resolve cycle import issue

**Review by CoderZhi — CHANGES_REQUESTED** [review]

**Review by CoderZhi — APPROVED** [review]
