### PR TITLE
[staking] correct handle nil bucket value

### LINKED ISSUE #3367: getAllBuckets returns nil at #3189
### What version of iotex-core are you using (`ioctl version`)?
latest master

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
start fullnode

### What did you expect to see?
success

### What did you see instead?
{"level":"fatal","ts":1651111204.7867224,"caller":"itx/server.go:178","msg":"Failed to start server.","ioAddr":"io195jaqf3yuty556xx33x9ln332sjhfj50w5u90p","error":"error when starting blockchain: failed to start child services: failed to start protocol *staking.Protocol: failed to start staking protocol: failed to deserialize bucket: value is nil","errorVerbose":"value is nil\ngithub.com/iotexproject/iotex-core/state.init\n\t/home/dustin/iotex-core/state/iterator.go:17\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6265\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6242\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6242\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6242\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:208\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to deserialize bucket\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*candSR).getAllBuckets\n\t/home/dustin/iotex-core/action/protocol/staking/candidate_statereader.go:260\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*candSR).NewBucketPool\n\t/home/dustin/iotex-core/action/protocol/staking/candidate_statereader.go:346\ngithub.com/iotexproject/iotex-core/action/protocol/staking.CreateBaseView\n\t/home/dustin/iotex-core/action/protocol/staking/candidate_statereader.go:194\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Protocol).Start\n\t/home/dustin/iotex-core/action/protocol/staking/protocol.go:163\ngithub.com/iotexproject/iotex-core/action/protocol.(*Registry).StartAll\n\t/home/dustin/iotex-core/action/protocol/registry.go:106\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Start\n\t/home/dustin/iotex-core/state/factory/statedb.go:166\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/home/dustin/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/dustin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to start staking protocol\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Protocol).Start\n\t/home/dustin/iotex-core/action/protocol/staking/protocol.go:165\ngithub.com/iotexproject/iotex-core/action/protocol.(*Registry).StartAll\n\t/home/dustin/iotex-core/action/protocol/registry.go:106\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Start\n\t/home/dustin/iotex-core/state/factory/statedb.go:166\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/home/dustin/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/dustin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to start protocol *staking.Protocol\ngithub.com/iotexproject/iotex-core/action/protocol.(*Registry).StartAll\n\t/home/dustin/iotex-core/action/protocol/registry.go:108\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).Start\n\t/home/dustin/iotex-core/state/factory/statedb.go:166\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/home/dustin/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/dustin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to start child services\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/home/dustin/iotex-core/blockchain/blockdao/blockdao.go:85\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/home/dustin/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/dustin/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/home/dustin/iotex-core/server/itx/server.go:101\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/home/dustin/iotex-core/server/itx/server.go:177\nmain.main\n\t/home/dustin/iotex-core/server/main.go:167\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}

### debug
1. the culprit is #3189, keep debugging
2. all tried adding #3364, it does not help
3. also it is weird the error happens around block height 5220000, seems to work fine in other height ranges

### PR DESCRIPTION
**Pull request by dustinxie**
# Description
as title

Fixes #3367 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
1. make test
2. fullsync

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: action/protocol/staking/candidate_statereader.go [hunk 1]
```diff
@@ -256,10 +256,13 @@ func (c *candSR) getAllBuckets() ([]*VoteBucket, uint64, error) {
 	buckets := make([]*VoteBucket, 0, iter.Size())
 	for i := 0; i < iter.Size(); i++ {
 		vb := &VoteBucket{}
-		if err := iter.Next(vb); err != nil {
+		switch err := iter.Next(vb); errors.Cause(err) {
+		case nil:
+			buckets = append(buckets, vb)
+		case state.ErrNilValue:
+		default:
```
Comment (dustinxie) [inline action/protocol/staking/candidate_statereader.go:263]: bug introduced by #3189

**Review by Liuhaai — APPROVED** [review]
