### PR TITLE
[context] tolerate empty candidate name

### LINKED ISSUE #4561: failed to commit block 21910804
### What version of iotex-core image (or code branch) are you using?
latest

### What operating system and processor architecture are you using?
macOS/Linux

### What did you do? If possible, provide a recipe for reproducing the error.
as title, full-node failed to commit block 21910804

### Root-cause
The culprit tx is https://iotexscan.io/tx/9d5bd12aa6b8bf7bc803b253f2dcc26abcd6980fa953491b1270dfdfbf64aacb, which is a `CandidateUpdate` but with empty name. It triggers the following error
```
func (cu *CandidateUpdate) SanityCheck() error {
    if !IsValidCandidateName(cu.Name()) {
        return ErrInvalidCanName
    }
    return nil
}
```
the check code is added by #3705, and was included in v1.10.0 release on Mar 23, 2023, which happened after the culprit tx

### PR DESCRIPTION
**Pull request by dustinxie**
# Description
as title, fix the following bug.

Fixes #4561 

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: blockchain/block/validator.go [hunk 1]
```diff
@@ -36,8 +37,11 @@ func (v *validator) Validate(ctx context.Context, blk *Block) error {
 
 	v.validateActions(ctx, actions, errChan)
 	close(errChan)
+	fCtx := protocol.MustGetFeatureCtx(ctx)
 	for err := range errChan {
-		return errors.Wrap(err, "failed to validate action")
+		if !fCtx.Tolerate(err) {
+			return errors.Wrap(err, "failed to validate action")
+		}
```
Comment (CoderZhi) [inline blockchain/block/validator.go:44]: it is inexplicit to handle the error here. https://github.com/iotexproject/iotex-core/blob/5d5e5afc1e9afaddcdfaf24bb47acc00f5aed126/action/protocol/generic_validator.go#L61

File: action/protocol/context.go [hunk 2]
```diff
@@ -307,6 +311,13 @@ func WithFeatureCtx(ctx context.Context) context.Context {
 	)
 }
 
+func (fCtx *FeatureCtx) Tolerate(err error) bool {
+	if fCtx.TolerateEmptyCandidateName && errors.Cause(err) == action.ErrInvalidCanName {
+		return true
+	}
+	return false
+}
```
Comment (CoderZhi) [inline action/protocol/context.go:319]: error type shouldn't not be included in a function which doesn't name it's functionality. https://github.com/iotexproject/iotex-core/blob/5d5e5afc1e9afaddcdfaf24bb47acc00f5aed126/action/protocol/generic_validator.go#L61 is a better place to handle the check

File: blockchain/block/validator.go (hunk 1 above)
Comment (dustinxie) [reply blockchain/block/validator.go:44]: generic_validator is used by actpool and factory/statedb, I think it should keep strict checking

this error is specifically for block.validator.Validate(blk), so want to capture the error here

File: action/protocol/context.go (hunk 2 above)
Comment (dustinxie) [reply action/protocol/context.go:319]: do you mean the func name is not clear? or should not check error type in this func?

**Review by envestcc — APPROVED** [review]

File: action/protocol/generic_validator.go [hunk 3]
```diff
@@ -58,7 +58,8 @@ func (v *GenericValidator) Validate(ctx context.Context, selp *action.SealedEnve
 	if caller == nil {
 		return errors.New("failed to get address")
 	}
-	if err = selp.Envelope.SanityCheck(); err != nil {
+	featureCtx := MustGetFeatureCtx(ctx)
+	if err = selp.Envelope.SanityCheck(); err != nil && !featureCtx.Tolerate(err) {
```
Comment (CoderZhi) [inline action/protocol/generic_validator.go:62]: `featureCtx.TolerateEmptyCandidateName && errors.Cause(err) == action.ErrInvalidCanName` shouldn't be hidden in a function of `FeatureCtx`.

**Review by CoderZhi — APPROVED** [review]

File: action/protocol/generic_validator.go (hunk 3 above)
Comment (dustinxie) [reply action/protocol/generic_validator.go:62]: I see, I was thinking in the future may have similar case again, so add a `Tolerate` for this kind of special case
