### PR TITLE
[db] Fix variadic interface bug

### LINKED ISSUE #3517: maybe a  bug in batch_impl.go, not expect behavior with Wrapf(e, errFmt, errArgs)
### What did you do? If possible, provide a recipe for reproducing the error.

i am writing a [linter](https://github.com/alingse/asasalint) to lint that pass []any as any in variadic function

and run github Actions for some top go packages, this package failed

see github actions lint result here https://github.com/alingse/asasalint/runs/7284520322?check_suite_focus=true

```
Error: /home/runner/work/asasalint/asasalint/iotex-core/db/batch/batch_impl.go:73:51: pass []any as any to func batch func(op github.com/iotexproject/iotex-core/db/batch.WriteType, namespace string, key []byte, value []byte, errorFormat string, errorArgs ...interface{})
Error: /home/runner/work/asasalint/asasalint/iotex-core/db/batch/batch_impl.go:80:52: pass []any as any to func batch func(op github.com/iotexproject/iotex-core/db/batch.WriteType, namespace string, key []byte, value []byte, errorFormat string, errorArgs ...interface{})
Error: /home/runner/work/asasalint/asasalint/iotex-core/db/batch/batch_impl.go:263:65: pass []any as any to func batch func(op github.com/iotexproject/iotex-core/db/batch.WriteType, namespace string, key []byte, value []byte, errorFormat string, errorArgs ...interface{})
Error: /home/runner/work/asasalint/asasalint/iotex-core/db/batch/batch_impl.go:273:66: pass []any as any to func batch func(op github.com/iotexproject/iotex-core/db/batch.WriteType, namespace string, key []byte, value []byte, errorFormat string, errorArgs ...interface{})
```

### PR DESCRIPTION
**Pull request by Liuhaai**
# Description
Fixes #3517 

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: db/batch/batch_impl.go [hunk 1]
```diff
@@ -270,7 +270,7 @@ func (cb *cachedBatch) Delete(namespace string, key []byte, errorFormat string,
 	h := cb.hash(namespace, key)
 	cb.touchKey(h)
 	cb.currentCache().Evict(&h)
-	cb.kvStoreBatch.batch(Delete, namespace, key, nil, errorFormat, errorArgs)
+	cb.kvStoreBatch.batch(Delete, namespace, key, nil, errorFormat, errorArgs...)
```
Comment (dustinxie) [inline db/batch/batch_impl.go:273]: this is prob not the complete fix, need to also change `errorArgs` to `[]interface{}`, and use `errorArgs...` when it is used in `WriteBatch`
see https://github.com/iotexproject/iotex-core/commit/010f0d08aa94a35a4aec943da5034167ad79be8b (also not complete, just demo the fix on `baseKVStoreBatch`)

**Review by CoderZhi — APPROVED** [review]

**Review by dustinxie — APPROVED** [review]
