### PR TITLE
use Address() API to simplify code #2749 fixed

### LINKED ISSUE #2749: use Address() API to simplify code
**What would you like to be added**:
replace
```
pubKey := prvKey.PublicKey()
addr, _ := address.FromBytes(pubKey.Hash())
```
with
```
addr := pubKey.Address()
```
**Why is this needed**:
1. the latest `go-pkgs` added `Address()` API to directly output the Address object given the public key
2. more concise code

### PR DESCRIPTION
**Pull request by ashishsnigam**
Fixed #2749 

1. Updated all (hopefully) instanced of public key calling to use Address()
2. Error check changed to check if address is not nil

### CODE REVIEW

File: actpool/actioniterator/actioniterator.go [hunk 1]
```diff
@@ -73,7 +71,7 @@ func NewActionIterator(accountActs map[string][]action.SealedEnvelope) ActionIte
 // LoadNext load next action of account of top action
 func (ai *actionIterator) loadNextActionForTopAccount() {
 	sender := ai.heads[0].SrcPubkey()
-	callerAddr, _ := address.FromBytes(sender.Hash())
+	callerAddr := sender.Address()
```
Comment (dustinxie) [inline actpool/actioniterator/actioniterator.go:74]: callerAddrStr := sender.Address().String()

File: state/factory/workingset.go [hunk 2]
```diff
@@ -128,9 +127,10 @@ func (ws *workingSet) runActions(
 
 func withActionCtx(ctx context.Context, selp action.SealedEnvelope) (context.Context, error) {
 	var actionCtx protocol.ActionCtx
-	caller, err := address.FromBytes(selp.SrcPubkey().Hash())
-	if err != nil {
-		return nil, err
+	var err error
```
Comment (dustinxie) [inline state/factory/workingset.go:130]: no need to define this?

File: actpool/actioniterator/actioniterator.go (hunk 1 above)
Comment (ashishsnigam) [reply actpool/actioniterator/actioniterator.go:74]: done

File: state/factory/workingset.go (hunk 2 above)
Comment (ashishsnigam) [reply state/factory/workingset.go:130]: I guess its needed for next line, actionCtx.ActionHash, err := selp.Hash()
As actionCtx variable is already defined, err also needs to be defined. Earlier it was working because err was getting defined in caller, err := address.FromBytes(selp.SrcPubkey().Hash()) which is removed now.

Comment (dustinxie) [reply state/factory/workingset.go:130]: i see, thx

File: tools/bot/server/bot/xrc20.go [hunk 3]
```diff
@@ -102,8 +101,8 @@ func (s *Xrc20) checkAndAlert(hs string) {
 	}
 }
 func (s *Xrc20) transfer(pri crypto.PrivateKey) (txhash string, err error) {
-	addr, err := address.FromBytes(pri.PublicKey().Hash())
-	if err != nil {
+	addr := pri.PublicKey().Address()
+	if addr == nil {
 		return
 	}
```
Comment (CoderZhi) [inline tools/bot/server/bot/xrc20.go:107]: err will be nil if not specified in return statement

File: tools/bot/server/bot/transfer.go [hunk 4]
```diff
@@ -93,8 +92,8 @@ func (s *Transfer) checkAndAlert(hs string) {
 	}
 }
 func (s *Transfer) transfer(pri crypto.PrivateKey) (txhash string, err error) {
-	addr, err := address.FromBytes(pri.PublicKey().Hash())
-	if err != nil {
+	addr := pri.PublicKey().Address()
+	if addr == nil {
 		return
```
Comment (CoderZhi) [inline tools/bot/server/bot/transfer.go:97]: same here

File: tools/bot/server/bot/execution.go [hunk 5]
```diff
@@ -103,8 +103,8 @@ func (s *Execution) checkAndAlert(hs string) {
 	}
 }
 func (s *Execution) exec(pri crypto.PrivateKey) (txhash string, err error) {
-	addr, err := address.FromBytes(pri.PublicKey().Hash())
-	if err != nil {
+	addr := pri.PublicKey().Address()
+	if addr == nil {
 		return
```
Comment (CoderZhi) [inline tools/bot/server/bot/execution.go:108]: and here

File: ioctl/newcmd/account/accountcreate.go [hunk 6]
```diff
@@ -65,9 +63,9 @@ func NewAccountCreate(c ioctl.Client) *cobra.Command {
 				if err != nil {
 					return output.NewError(output.CryptoError, failToGenerateNewPrivateKey, err)
 				}
-				addr, err := address.FromBytes(private.PublicKey().Hash())
-				if err != nil {
-					return output.NewError(output.ConvertError, failToConvertPublicKeyIntoAddress, err)
+				addr := private.PublicKey().Address()
+				if addr == nil {
+					return output.NewError(output.ConvertError, failToConvertPublicKeyIntoAddress, nil)
```
Comment (CoderZhi) [inline ioctl/newcmd/account/accountcreate.go:68]: will the replacement of err with "nil" work?

**Review by CoderZhi — COMMENTED** [review]
it seems like we should panic if the address cannot be derived from a public key?

File: ioctl/newcmd/account/accountcreate.go (hunk 6 above)
Comment (dustinxie) [reply ioctl/newcmd/account/accountcreate.go:68]: yes, if there's error, returned `addr` will be nil

Comment (ashishsnigam) [reply ioctl/newcmd/account/accountcreate.go:68]: @dustinxie @CoderZhi I guess no more change is required at my end so I updated the branch with latest master. Please review this PR.

File: tools/util/injectorutil.go [hunk 7]
```diff
@@ -728,9 +727,9 @@ func CheckPendingActionList(
 						retErr = err
 						return false
 					}
-					executoraddr, err := address.FromBytes(selp.SrcPubkey().Hash())
-					if err != nil {
-						retErr = err
+					executoraddr := selp.SrcPubkey().Address()
+					if executoraddr != nil {
```
Comment (dustinxie) [inline tools/util/injectorutil.go:731]: == nil
this is why test failed

Comment (dustinxie) [reply tools/util/injectorutil.go:731]: also pls fix @CoderZhi 's comments above

Comment (ashishsnigam) [reply tools/util/injectorutil.go:731]: ahh.. I missed it. fixed. == nil

File: ioctl/newcmd/account/accountcreate.go (hunk 6 above)
Comment (ashishsnigam) [reply ioctl/newcmd/account/accountcreate.go:68]: > will the replacement of err with "nil" work?

return output.NewError(output.AddressError, failToConvertPublicKeyIntoAddress, nil)

File: tools/bot/server/bot/xrc20.go (hunk 3 above)
Comment (ashishsnigam) [reply tools/bot/server/bot/xrc20.go:107]: done

File: tools/bot/server/bot/transfer.go (hunk 4 above)
Comment (ashishsnigam) [reply tools/bot/server/bot/transfer.go:97]: done

File: tools/bot/server/bot/execution.go (hunk 5 above)
Comment (ashishsnigam) [reply tools/bot/server/bot/execution.go:108]: done

File: tools/util/injectorutil.go (hunk 7 above)
Comment (ashishsnigam) [reply tools/util/injectorutil.go]: > also fix @CoderZhi 's comments above

changes done

**Review by dustinxie — APPROVED** [review]

**Review by CoderZhi — APPROVED** [review]
