### PR TITLE
fix ioctl update failed on mac

### LINKED ISSUE #3955: ioctl update sometimes fail
### What version of iotex-core image (or code branch) are you using?
latest

### What operating system and processor architecture are you using?
macOS

### What did you do? If possible, provide a recipe for reproducing the error.
`ioctl update`

### What did you expect to see?
successfully download and update to latest release version

### What did you see instead?
Error: failed to update ioctl: exit status 1

### PR DESCRIPTION
**Pull request by millken**
# Description
The reason why the ioctl update failed on mac is that install-cli.sh requires root privileges to execute.

Fixes #3955

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: install-cli.sh [hunk 1]
```diff
@@ -122,27 +122,20 @@ else
 fi
 
 if [ "${OS}" = "darwin" ];then
-    if test -x "$(command -v brew)"; then
+    if test -x "$(command -v brew)"; then
```
Comment (dustinxie) [inline install-cli.sh:125]: remove space?

**Review by dustinxie — APPROVED** [review]

**Review by envestcc — APPROVED** [review]
