### PR TITLE
fix filter bug in kvstorewithbuffer

### LINKED ISSUE #3257: fullsync issue at Greenland height
### What version of iotex-core are you using (`ioctl version`)?
latest master code

### What did you do? If possible, provide a recipe for reproducing the error.
latest master code failed the fullsync test at Greenland height, after triage, it erred at this commit: https://github.com/iotexproject/iotex-core/commit/f2b6347053a4bbcc8a0e59b94a68291e8e8d3f6b

### What did you see instead?
fullsync test can pass with previous commit, but erred at this commit
block 6544441 (Greenland height) cannot commit, gives error:
`{"level":"fatal","ts":1649226141.2777076,"caller":"itx/server.go:180","msg":"Failed to start server.","ioAddr":"io1f57cjqa9vfk4adkput3g8e8kzmmf5upyxw5faz","error":"error when starting blockchain: error when starting blockchain: failed to deserialize candidate: hrp  and address prefix io don't match: checksum failed: Expected fnl385, got 007728..","errorVerbose":"checksum failed: Expected fnl385, got 007728..\ngithub.com/iotexproject/iotex-address/address/bech32.Decode\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/bech32/bech32.go:87\ngithub.com/iotexproject/iotex-address/address.(*v1).decodeBech32\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address_v1.go:70\ngithub.com/iotexproject/iotex-address/address.(*v1).FromString\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address_v1.go:33\ngithub.com/iotexproject/iotex-address/address.FromString\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address.go:47\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Candidate).fromProto\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:196\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Candidate).Deserialize\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:174\ngithub.com/iotexproject/iotex-core/state.Deserialize\n\t/go/apps/iotex-core/state/state.go:51\ngithub.com/iotexproject/iotex-core/state.(*iterator).Next\n\t/go/apps/iotex-core/state/iterator.go:50\ngithub.com/iotexproject/iotex-core/action/protocol/staking.getAllCandidates\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:336\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).calculateVoteWeight\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:69\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).Revise\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:35\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Protocol).CreatePreStates\n\t/go/apps/iotex-core/action/protocol/staking/protocol.go:236\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).process\n\t/go/apps/iotex-core/state/factory/workingset.go:386\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/go/apps/iotex-core/state/factory/workingset.go:521\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).PutBlock\n\t/go/apps/iotex-core/state/factory/statedb.go:369\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).checkIndexers\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:154\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:105\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nhrp  and address prefix io don't match\ngithub.com/iotexproject/iotex-address/address.(*v1).decodeBech32\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address_v1.go:72\ngithub.com/iotexproject/iotex-address/address.(*v1).FromString\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address_v1.go:33\ngithub.com/iotexproject/iotex-address/address.FromString\n\t/go/pkg/mod/github.com/iotexproject/iotex-address@v0.2.6/address/address.go:47\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Candidate).fromProto\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:196\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Candidate).Deserialize\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:174\ngithub.com/iotexproject/iotex-core/state.Deserialize\n\t/go/apps/iotex-core/state/state.go:51\ngithub.com/iotexproject/iotex-core/state.(*iterator).Next\n\t/go/apps/iotex-core/state/iterator.go:50\ngithub.com/iotexproject/iotex-core/action/protocol/staking.getAllCandidates\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:336\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).calculateVoteWeight\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:69\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).Revise\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:35\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Protocol).CreatePreStates\n\t/go/apps/iotex-core/action/protocol/staking/protocol.go:236\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).process\n\t/go/apps/iotex-core/state/factory/workingset.go:386\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/go/apps/iotex-core/state/factory/workingset.go:521\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).PutBlock\n\t/go/apps/iotex-core/state/factory/statedb.go:369\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).checkIndexers\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:154\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:105\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to deserialize candidate\ngithub.com/iotexproject/iotex-core/action/protocol/staking.getAllCandidates\n\t/go/apps/iotex-core/action/protocol/staking/candidate.go:337\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).calculateVoteWeight\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:69\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*VoteReviser).Revise\n\t/go/apps/iotex-core/action/protocol/staking/vote_reviser.go:35\ngithub.com/iotexproject/iotex-core/action/protocol/staking.(*Protocol).CreatePreStates\n\t/go/apps/iotex-core/action/protocol/staking/protocol.go:236\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).process\n\t/go/apps/iotex-core/state/factory/workingset.go:386\ngithub.com/iotexproject/iotex-core/state/factory.(*workingSet).ValidateBlock\n\t/go/apps/iotex-core/state/factory/workingset.go:521\ngithub.com/iotexproject/iotex-core/state/factory.(*stateDB).PutBlock\n\t/go/apps/iotex-core/state/factory/statedb.go:369\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).checkIndexers\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:154\ngithub.com/iotexproject/iotex-core/blockchain/blockdao.(*blockDAO).Start\n\t/go/apps/iotex-core/blockchain/blockdao/blockdao.go:105\ngithub.com/iotexproject/iotex-core/pkg/lifecycle.(*Lifecycle).OnStart.func1\n\t/go/apps/iotex-core/pkg/lifecycle/lifecycle.go:56\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/chainservice.(*ChainService).Start\n\t/go/apps/iotex-core/chainservice/chainservice.go:450\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:98\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:179\nmain.main\n\t/go/apps/iotex-core/server/main.go:167\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror when starting blockchain\ngithub.com/iotexproject/iotex-core/server/itx.(*Server).Start\n\t/go/apps/iotex-core/server/itx/server.go:99\ngithub.com/iotexproject/iotex-core/server/itx.StartServer\n\t/go/apps/iotex-core/server/itx/server.go:179\nmain.main\n\t/go/apps/iotex-core/server/main.go:167\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
`

### How to repro?
1. chain DB files: gs://blockchain-golden/mainnet-chaindb/chain-00000006.db
2. trie.db file: gs://blockchain-golden/fullsync/trie.6544440
3. start a fullnode, you will see the above error
4. go back to previous commit, it can commit block 6544441 successfully

### PR DESCRIPTION
**Pull request by CoderZhi**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3257

## Type of change

Please delete options that are not relevant.

- [*] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- None

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Liuhaai — APPROVED** [review]

File: action/protocol/poll/util.go [hunk 1]
```diff
@@ -318,9 +318,9 @@ func setCurrentBlockMeta(
 
 // allBlockMetasFromDB returns all latest block meta structs
 func allBlockMetasFromDB(sr protocol.StateReader, blocksInEpoch uint64) ([]*BlockMeta, error) {
-	keys := [][]byte{blockMetaKey(math.MaxUint64, blocksInEpoch)}
+	keys := make([][]byte, blocksInEpoch)
```
Comment (dustinxie) [inline action/protocol/poll/util.go:321]: `math.MaxUint64` corresponds to max key in old code (using `Filter`)
now switch to use `keys`, it is not needed

File: state/factory/workingsetstore.go [hunk 2]
```diff
@@ -108,7 +110,10 @@ func (store *stateDBWorkingSetStore) Delete(ns string, key []byte) error {
 }
 
 func (store *stateDBWorkingSetStore) States(ns string, keys [][]byte) ([][]byte, error) {
-	return readStates(store.flusher.KVStoreWithBuffer(), ns, keys)
+	if store.readBuffer {
+		return readStates(store.flusher.KVStoreWithBuffer(), ns, keys)
```
Comment (dustinxie) [inline state/factory/workingsetstore.go:114]: after the 180 HF, we can revert `readBuffer`, and always go
```
readStates(store.flusher.KVStoreWithBuffer(), ns, keys)
```

**Review by dustinxie — APPROVED** [review]
