### PR TITLE
[api] fix revert message in eth_call

### LINKED ISSUE #3821: `eth_call` return error response when revert
### What version of iotex-core image (or code branch) are you using?

all version

### Example contract code

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.12;

contract Error {
    error Test(uint256 input);

    function noerror(uint input) public pure returns (bool) {
        if (input == 0) {
            return true;
        }

        if (input == 1) {
            require(input == 2, "require test");
        }

        if (input == 2) {
            revert("revert test");
        }

        revert Test(input);
    }
}
```

### What did you do? If possible, provide a recipe for reproducing the error.

```
curl -X POST https://babel-api.testnet.iotex.io -H "Content-Type:application/json" --data '{
    "jsonrpc":"2.0",
                "method":"eth_call",
                "params":[{
                       "from": "0x0000000000000000000000000000000000000000",
                       "to": "0x39C1088120741C48D09D88a0DbcF3E757F5fcA22",
                       "data": "0x08335c900000000000000000000000000000000000000000000000000000000000000001"
                }],
    "id":1
}'
```

### What did you expect to see?

```
{
    "jsonrpc":"2.0",
    "id":1,
    "error":{
         "code":3,
         "message":"execution reverted: require test",
         "data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c7265717569726520746573740000000000000000000000000000000000000000"
    }
}
```

### What did you see instead?

```
{
    "jsonrpc":"2.0",
    "id":1
    "result":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c7265717569726520746573740000000000000000000000000000000000000000"
}
````

### PR DESCRIPTION
**Pull request by millken**
# Description
This PR is part of PR #3921 about issue #3821

Fixes #3821

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: api/web3server_marshal.go [hunk 1]
```diff
@@ -29,8 +29,9 @@ type (
 	}
 
 	errMessage struct {
-		Code    int    `json:"code"`
-		Message string `json:"message"`
+		Code    int         `json:"code"`
+		Message string      `json:"message"`
+		Data    interface{} `json:"data,omitempty"`
```
Comment (dustinxie) [inline api/web3server_marshal.go:34]: revert, do this in PR3920

**Review by dustinxie — APPROVED** [review]

File: api/web3server_marshal.go (hunk 1 above)
Comment (millken) [reply api/web3server_marshal.go:34]: can not be reverted, expected API response needs to this `Data`

**Review by envestcc — APPROVED** [review]
