### PR TITLE
[evm] fix RevertSnapshot

### LINKED ISSUE #4491: API call return "Failed to snapshot" error
### What version of iotex-core image (or code branch) are you using?
latest

### What operating system and processor architecture are you using?
Linux/macOS

### What did you do? If possible, provide a recipe for reproducing the error.
curl https://babel-api.mainnet.iotex.io/ -i \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{
    "method":"eth_call",
    "params":[
        {
            "to":"0x7a524c7e82874226f0b51aade60a1be4d430cf0f",
            "data":"0x63fb0b96000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000300000000000000000000000034bc1b87f60e0a30c0e24fd7abada70436c7140600000000000000000000000034bc1b87f60e0a30c0e24fd7abada70436c7140600000000000000000000000034bc1b87f60e0a30c0e24fd7abada70436c71406000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000000000c40980929e0000000000000000000000000000000000000000000000056bc75e2d63100000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000422d9526e2cabd30c6e8f89ea60d230503c59c6603000bb8a00744882684c3e4747faefd68d283ea44099d03000bb8cdf79194c6c285077a58da47641d4dbe51f635420000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c40980929e0000000000000000000000000000000000000000000000056bc75e2d63100000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000592d9526e2cabd30c6e8f89ea60d230503c59c6603000bb8a00744882684c3e4747faefd68d283ea44099d03000bb8a1a1531f6ae90192edcc32e9f38e98f3037081440001f4cdf79194c6c285077a58da47641d4dbe51f63542000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40980929e0000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002b2d9526e2cabd30c6e8f89ea60d230503c59c66030001f4cdf79194c6c285077a58da47641d4dbe51f6354200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
        }, "0x1facde6"
        ],
    "id":1,
    "jsonrpc":"2.0"
}'

### What did you expect to see?
success

### What did you see instead?
	
{"level":"panic","ts":"2024-11-17T05:49:39.424Z","caller":"evm/evmstatedbadapter.go:760","msg":"Failed to snapshot.","ioAddr":"io167ysqrwqwc4z827zd5g7k9q3rh9cr834e2xufv","error":"unexpected error: duplicate snapshot version","errorVerbose":"unexpected error: duplicate snapshot version\[ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.(*StateDBAdapter).Snapshot\n\t/go/apps/iotex-core/action/protocol/execution/evm/evmstatedbadapter.go:758\ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:189\ngithub.com/ethereum/go-ethereum/core/vm.opCall\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669\ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234\ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241\ngithub.com/ethereum/go-ethereum/core/vm.opCall\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669\ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234\ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241\ngithub.com/ethereum/go-ethereum/core/vm.opCall\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669\ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234\ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call\n\t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241\ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.executeInEVM\n\t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:480\ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.ExecuteContract\n\t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:248\ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.SimulateExecution\n\t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:646\ngithub.com/iotexproject/iotex-core/v2/state/factory.(*stateDB).SimulateExecution\n\t/go/apps/iotex-core/state/factory/statedb.go:291\ngithub.com/iotexproject/iotex-core/v2/api.(*coreService).simulateExecution\n\t/go/apps/iotex-core/api/coreservice.go:1975\ngithub.com/iotexproject/iotex-core/v2/api.(*coreService).ReadContract\n\t/go/apps/iotex-core/api/coreservice.go:560\ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).call\n\t/go/apps/iotex-core/api/web3server.go:424\ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).handleWeb3Req\n\t/go/apps/iotex-core/api/web3server.go:174\ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).HandlePOSTReq\n\t/go/apps/iotex-core/api/web3server.go:121\ngithub.com/iotexproject/iotex-core/v2/api.(*hTTPHandler).ServeHTTP\n\t/go/apps/iotex-core/api/http.go:71\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2514\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2009\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650](http://ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.(*StateDBAdapter).Snapshot/n/t/go/apps/iotex-core/action/protocol/execution/evm/evmstatedbadapter.go:758/ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:189/ngithub.com/ethereum/go-ethereum/core/vm.opCall/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669/ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234/ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241/ngithub.com/ethereum/go-ethereum/core/vm.opCall/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669/ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234/ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241/ngithub.com/ethereum/go-ethereum/core/vm.opCall/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/instructions.go:669/ngithub.com/ethereum/go-ethereum/core/vm.(*EVMInterpreter).Run/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/interpreter.go:234/ngithub.com/ethereum/go-ethereum/core/vm.(*EVM).Call/n/t/go/pkg/mod/github.com/iotexproject/go-ethereum@v0.5.0/core/vm/evm.go:241/ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.executeInEVM/n/t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:480/ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.ExecuteContract/n/t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:248/ngithub.com/iotexproject/iotex-core/v2/action/protocol/execution/evm.SimulateExecution/n/t/go/apps/iotex-core/action/protocol/execution/evm/evm.go:646/ngithub.com/iotexproject/iotex-core/v2/state/factory.(*stateDB).SimulateExecution/n/t/go/apps/iotex-core/state/factory/statedb.go:291/ngithub.com/iotexproject/iotex-core/v2/api.(*coreService).simulateExecution/n/t/go/apps/iotex-core/api/coreservice.go:1975/ngithub.com/iotexproject/iotex-core/v2/api.(*coreService).ReadContract/n/t/go/apps/iotex-core/api/coreservice.go:560/ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).call/n/t/go/apps/iotex-core/api/web3server.go:424/ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).handleWeb3Req/n/t/go/apps/iotex-core/api/web3server.go:174/ngithub.com/iotexproject/iotex-core/v2/api.(*web3Handler).HandlePOSTReq/n/t/go/apps/iotex-core/api/web3server.go:121/ngithub.com/iotexproject/iotex-core/v2/api.(*hTTPHandler).ServeHTTP/n/t/go/apps/iotex-core/api/http.go:71/ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP/n/t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212/nnet/http.(*ServeMux).ServeHTTP/n/t/usr/local/go/src/net/http/server.go:2514/nnet/http.serverHandler.ServeHTTP/n/t/usr/local/go/src/net/http/server.go:2938/nnet/http.(*conn).serve/n/t/usr/local/go/src/net/http/server.go:2009/nruntime.goexit/n/t/usr/local/go/src/runtime/asm_amd64.s:1650)"}

### PR DESCRIPTION
**Pull request by dustinxie**
# Description
as title.

Fixes #4491

## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Code refactor or improvement
- [] Breaking change (fix or feature that would cause a new or changed behavior of existing functionality)
- [] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- [x] make test
- [] fullsync
- [] Other test (please specify)

**Test Configuration**:
- Firmware version:
- Hardware:
- Toolchain:
- SDK:

# Checklist:
- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [] New and existing unit tests pass locally with my changes
- [] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by envestcc — COMMENTED** [review]
Changes after HF looks good to me, what about fix before HF?

**Review by CoderZhi — APPROVED** [review]

**Comment by CoderZhi** [comment]
> Changes after HF looks good to me, what about fix before HF?

No fix is needed before HF, IMO

File: action/protocol/execution/evm/evm.go [hunk 1]
```diff
@@ -376,7 +376,9 @@ func prepareStateDB(ctx context.Context, sm protocol.StateManager) (*StateDBAdap
 	if featureCtx.EnableCancunEVM {
 		opts = append(opts, EnableCancunEVMOption())
 	}
-
+	if featureCtx.FixRevertSnapshot {
```
Comment (dustinxie) [inline action/protocol/execution/evm/evm.go:379]: wait PR4494 to merge, then check the `ReadOnly` here

**Review by envestcc — APPROVED** [review]
