### PR TITLE
[api] fix issue#3030

### LINKED ISSUE #3030: web3 rpc `eth_accounts` should return empty account replace error

### PR DESCRIPTION
**Pull request by Liuhaai**
fix #3030

### CODE REVIEW

**Review by dustinxie — APPROVED** [review]

File: api/web3server.go [hunk 1]
```diff
@@ -175,6 +175,8 @@ func (svr *Web3Server) handlePOSTReq(req *http.Request) interface{} {
 			method = web3Req.Get("method").Value()
 		)
 		switch method {
+		case "eth_accounts":
+			res, err = svr.ethAccounts()
```
Comment (CoderZhi) [inline api/web3server.go:179]: for a method as simple as this one, why not leave the code here?
`res = []string{}`
question: empty address == []string{} ?

Comment (Liuhaai) [reply api/web3server.go:179]: https://infura.io/docs/ethereum/json-rpc/eth-accounts
`[]` should be returned.

Comment (Liuhaai) [reply api/web3server.go:179]: Adding a subfunc is friendly for testing and extension in the future.

**Review by millken — APPROVED** [review]
