### PR TITLE
fix nil filter input in GetLogs and StreamLogs

### LINKED ISSUE #2318: nil pointer in api
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xf68cdd]

goroutine 4892 [running]:
github.com/iotexproject/iotex-core/api.(*LogFilter).match(0xc0000238e8, 0xc0002a8750, 0xc00014c160)
	/go/apps/iotex-core/api/logfilter.go:82 +0x3d
github.com/iotexproject/iotex-core/api.(*LogFilter).MatchLogs(0xc0000238e8, 0xc000010fc0, 0x1, 0x1, 0x1, 0x0, 0x0)
	/go/apps/iotex-core/api/logfilter.go:72 +0xc2
github.com/iotexproject/iotex-core/api.(*Server).getLogsInBlock(0xc00002f800, 0xc0000238e8, 0x4e2a, 0x1, 0x9f9f2e2c336ae474, 0x1aa4778becb4743, 0x0, 0x0, 0x3)
	/go/apps/iotex-core/api/api.go:1359 +0x220
github.com/iotexproject/iotex-core/api.(*Server).GetLogs(0xc00002f800, 0x16be9a0, 0xc00120e7e0, 0xc0013fa0c0, 0xc00002f800, 0x7f28b02b1e00, 0xc0002e17c0)
```

### PR DESCRIPTION
**Pull request by yutongp**
fix #2318 in api level

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -650,14 +650,17 @@ func (api *Server) GetLogs(
 	ctx context.Context,
 	in *iotexapi.GetLogsRequest,
 ) (*iotexapi.GetLogsResponse, error) {
+	if in.GetFilter() == nil {
```
Comment (raullenchai) [inline api/api.go:653]: any chance in == nil?


same below

Comment (yutongp) [reply api/api.go:653]: https://github.com/iotexproject/iotex-proto/blob/master/golang/iotexapi/api.pb.go#L2423

it is okay
